preset: recommended
risky: true
enabled:
  - declare_strict_types
  - dir_constant
  - unalign_double_arrow
  - no_superfluous_phpdoc_tags
disabled:
  - align_double_arrow
  - align_phpdoc
  - phpdoc_align
