language: php

php:
- 7.2
- 7.3
- 7.4

install: composer install --dev --no-interaction

script:
- vendor/bin/phpunit --coverage-clover=coverage.xml
- vendor/bin/phpstan analyse --memory-limit=2048M

after_success:
- bash <(curl -s https://codecov.io/bash)
